name: Build

on:
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Build
      run: |
        make
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: VOID
        path: ./build
